apiVersion: apps/v1

kind: Deployment

metadata:
  name: gpu-healthcheck

spec:

  replicas: 1

  selector:
    matchLabels:
      app: gpu-healthcheck

  template:

    metadata:

      labels:
        app: gpu-healthcheck

    spec:

      containers:

      - name: gpu-healthcheck

        image: gpu-healthcheck:latest

        ports:

        - containerPort: 8000

        - containerPort: 9100