apiVersion: monitoring.coreos.com/v1

kind: ServiceMonitor

metadata:
  name: gpu-healthcheck

spec:

  selector:

    matchLabels:
      app: gpu-healthcheck

  endpoints:

  - port: metrics
    interval: 30s