apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: gpu-healthcheck
spec:
  selector:
    matchLabels:
      app: gpu-healthcheck
  template:
    metadata:
      labels:
        app: gpu-healthcheck
    spec:
      hostPID: true
      containers:
      - name: gpu-healthcheck
        image: gpu-healthcheck:latest
        securityContext:
          privileged: true